name: digital_frame
description: A digital photo frame app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Image & File Handling
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  
  # System Features
  wakelock_plus: ^1.2.0
  shared_preferences: ^2.2.2
  
  # Background & Scheduling
  android_alarm_manager_plus: ^4.0.3
  # workmanager: ^0.5.2  ← KALDIR! (kullanmıyoruz)
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true